traffic_control_cleanup: false

# List of bandwidth limit and latency definitions
traffic_control_rules: []
traffic_control_rules_post_raw_cmds: []

# Path where the script will be placed
traffic_control_script_path_up: /usr/local/bin/traffic_control_up.sh
traffic_control_script_path_down: /usr/local/bin/traffic_control_down.sh

# Name of the systemd service
traffic_control_service_name: traffic-control.service

#
# Example of how to define traffic control network limits
#
# traffic_control_rules:
#  - interface: eth0
#    rate_upload: 10mbit
#    rate_download: 10mbit
#    latency: 100ms
#    jitter: 10ms
#    loss: 0.1%
#  - interface: eth1
#    rate_upload: 10mbit
#    rate_download: 10mbit
#  - interface: eth2
#    rate_upload: 100mbit
#    rate_download: 10mbit
#    latency: 50ms
#  - interface: eth3
#    state: absent
