geth_user: geth
geth_datadir: /data/geth
geth_auth_jwt_path: /data/execution-auth.secret
geth_announced_ip: "{{ ansible_host }}"

geth_cleanup: false # when set to "true" it will remove the container

geth_ports_p2p: 30303
geth_ports_http_rpc: 8545
geth_ports_engine: 8551
geth_ports_metrics: 6060

geth_container_name: geth
geth_container_image: ethereum/client-go:stable
geth_container_env: {}
geth_container_ports:
  - "127.0.0.1:{{ geth_ports_http_rpc }}:{{ geth_ports_http_rpc }}"
  - "127.0.0.1:{{ geth_ports_engine }}:{{ geth_ports_engine }}"
  - "{{ geth_ports_p2p }}:{{ geth_ports_p2p }}"
  - "{{ geth_ports_p2p }}:{{ geth_ports_p2p }}/udp"
geth_container_volumes:
  - "{{ geth_datadir }}:/data"
  - "{{ geth_auth_jwt_path }}:/execution-auth.jwt:ro"
geth_container_security_opts: []
geth_container_stop_timeout: "300"
geth_container_networks: []
geth_container_command:
  - --datadir=/data
  - --port={{ geth_ports_p2p }}
  - --http
  - --http.addr=0.0.0.0
  - --http.port={{ geth_ports_http_rpc }}
  - --authrpc.addr=0.0.0.0
  - --authrpc.port={{ geth_ports_engine }}
  - --authrpc.vhosts=*
  - --authrpc.jwtsecret=/execution-auth.jwt
  - --nat=extip:{{ geth_announced_ip }}
  - --metrics
  - --metrics.port={{ geth_ports_metrics }}
  - --metrics.addr=0.0.0.0
geth_container_command_extra_args: []
#  - --http.api=eth,net,web3
#  - --http.vhosts=*

# Only required changing when running custom networks
geth_init_custom_network: false
geth_init_autoremove_enabled: false
geth_init_custom_network_genesis_file: /config/genesis.json
geth_init_custom_network_container_env: {}
geth_init_custom_network_container_volumes:
  - "{{ geth_datadir }}:/data"
  - "{{ geth_init_custom_network_genesis_file }}:/genesis.json:ro"
geth_init_custom_network_container_command:
  - --datadir=/data
  - init
  - /genesis.json

# Default image pull policy
geth_container_pull: false
