ethereum_node_skip_cleanup: true
ethereum_node_announced_ip: 127.0.0.1
docker_daemon_options: # noqa: var-naming[no-role-prefix]
  storage-driver: "vfs"
# Fixes for integration tests to be able to run
lighthouse_container_command_extra_args: # noqa: var-naming[no-role-prefix]
# Fixes: Failed to start beacon node reason: Syncing from genesis is insecure and
# incompatible with data availability checks. You should instead perform a checkpoint
# sync from a trusted node using the --checkpoint-sync-url option. For a list of public endpoints,
#  see: https://eth-clients.github.io/checkpoint-sync-endpoints/
# Alternatively, use --allow-insecure-genesis-sync if the risks are understood.",
  - --allow-insecure-genesis-sync
teku_container_command_extra_args: # noqa: var-naming[no-role-prefix]
  # Fixes: Cannot sync outside of weak subjectivity period.
  # Consider re-syncing your node using --checkpoint-sync-url or use --ignore-weak-subjectivity-period-enabled to ignore this check
  - --ignore-weak-subjectivity-period-enabled
