- name: Remove teku container
  community.docker.docker_container:
    name: "{{ teku_container_name }}"
    state: absent
  when: teku_cleanup or (not teku_enabled)

- name: Remove teku validator container
  community.docker.docker_container:
    name: "{{ teku_validator_container_name }}"
    state: absent
  when: teku_cleanup or teku_enabled
