- name: Validate inputs
  ansible.builtin.import_tasks: validations.yaml

- name: Cleanup teku
  ansible.builtin.import_tasks: cleanup.yaml

- name: Setup teku
  ansible.builtin.import_tasks: setup.yaml
  when: not teku_cleanup
