collections:
  - name: community.docker
    version: "5.0.6"
  - name: ansible.posix
    version: "2.1.0"
  - name: community.general
    version: "12.4.0"

roles:
  - name: geerlingguy.docker
    version: "8.0.0"
  - src: geerlingguy.pip
    version: "3.1.2"
  - name: gantsign.oh-my-zsh
    version: "2.7.0"
  - name: gantsign.golang
    version: "3.5.0"
