collections:
  - name: community.docker
    version: ">=3.0.2,<4.0.0"
  - name: ansible.posix
    version: ">=1.4.0,<2.0.0"
  - name: community.general
    version: ">=6.0.0,<7.0.0"

roles:
  - name: geerlingguy.docker
    version: "6.0.3"
  - src: geerlingguy.pip
    version: "2.2.0"
