collections:
  - name: community.docker
    version: "3.12.1"
  - name: ansible.posix
    version: "1.5.4"
  - name: community.general
    version: "6.6.9"

roles:
  - name: geerlingguy.docker
    version: "6.0.3"
  - src: geerlingguy.pip
    version: "2.2.0"
  - name: gantsign.oh-my-zsh
    version: "2.4.0"
  - name: gantsign.golang
    version: "3.4.0"
