- name: Add charon user
  ansible.builtin.user:
    name: "{{ charon_user }}"
  register: charon_user_meta

- name: Create data dir
  ansible.builtin.file:
    path: "{{ charon_datadir }}"
    state: directory
    mode: "0750"
    owner: "{{ charon_user }}"
    group: "{{ charon_user }}"

- name: Set permissions
  ansible.builtin.command: "chown -R {{ charon_user }}:{{ charon_user }} {{ charon_datadir }}" # noqa no-free-form
  changed_when: false

- name: Run charon container
  community.docker.docker_container:
    name: "{{ charon_container_name }}"
    image: "{{ charon_container_image }}"
    image_name_mismatch: recreate
    state: started
    restart_policy: always
    stop_timeout: "{{ charon_container_stop_timeout }}"
    ports: "{{ charon_container_ports }}"
    volumes: "{{ charon_container_volumes }}"
    env: "{{ charon_container_env }}"
    networks: "{{ charon_container_networks }}"
    entrypoint: "{{ charon_container_entrypoint | default(omit) }}"
    command: "{{ charon_container_command | default(omit) }}"
    user: "{{ charon_user_meta.uid }}"
    pull: "{{ charon_container_pull | bool }}"
    security_opts: "{{ charon_container_security_opts }}"
