# Used to cleanup the hive installation
hive_cleanup: false

hive_repo_address: "https://github.com/ethereum/hive.git"
hive_repo_version: "master"
hive_repo_remote: "origin"

hive_systemd_service_name: "hive.service"

hive_dir: "/data/hive"
hive_dir_bin: "{{ hive_dir }}/bin"
hive_dir_source: "{{ hive_dir }}/src"
hive_dir_scripts: "{{ hive_dir }}/scripts"
hive_dir_results: "{{ hive_dir }}/results"
hive_dir_web: "{{ hive_dir }}/web"

hive_container_www_name: "nginx-hive"
hive_container_www_image: "nginx:1.27.3-alpine"
hive_container_www_env: {}
hive_container_www_ports:
  - "127.0.0.1:8080:80"
hive_container_www_volumes:
  - "{{ hive_dir_web }}:/usr/share/nginx/html"
  - "{{ hive_dir_results }}:/usr/share/nginx/html/results"
hive_container_www_networks: []
hive_container_www_restart_policy: "always"
hive_container_www_stop_timeout: 10


hive_simulations:
  # Always pull / build the latest container images
  always_pull_images: true
  # Global flags provided to all test runs
  global_flags:
    - --docker.nocache=.
    - --sim.loglevel=3
    - --loglevel=3
  # Exclude these containers from cleanup /
  container_cleanup_exclusions:
    - telegraf
    - nginx
    - logsprout
    - papertrail
    - rsyslog
    - vector
    - node_exporter
    - prometheus
    - grafana
  # Prune test results older than this value
  prune_test_results_older_than: 720h # 30 days
  # Tests to run
  tests:
    # Sync tests
    - simulator: ethereum/sync
      clients:
        - besu
        - erigon
        - ethereumjs
        - go-ethereum
        - nethermind
        - nimbus-el
        - reth
      extra_flags:
        - --client.checktimelimit=60s
        # - --sim.timelimit=10m

    # # GraphQL tests (only supported by besu, geth, nimbus-el)
    # - simulator: ethereum/graphql
    #   clients:
    #     - besu
    #     - go-ethereum
    #     - nimbus-el
    #   extra_flags:
    #     - --client.checktimelimit=60s
    #     - --sim.timelimit=5m

    # # DevP2P tests
    # - simulator: devp2p
    #   clients:
    #     - besu
    #     - erigon
    #     - ethereumjs
    #     - go-ethereum
    #     - nethermind
    #     - nimbus-el
    #     - reth
    #   extra_flags:
    #     - --client.checktimelimit=60s
    #     - --sim.timelimit=10m

    # # Pyspec tests
    # - simulator: ethereum/pyspec
    #   clients:
    #     - besu
    #     - erigon
    #     - ethereumjs
    #     - go-ethereum
    #     - nethermind
    #     - nimbus-el
    #     - reth
    #   extra_flags:
    #     - --client.checktimelimit=3m
    #     - --sim.timelimit=60s
    #     - --sim.parallelism=4

    # # RPC tests
    # - simulator: ethereum/rpc$
    #   clients:
    #     - besu
    #     - erigon
    #     - ethereumjs
    #     - go-ethereum
    #     - nethermind
    #     - nimbus-el
    #     - reth
    #   extra_flags:
    #     - --client.checktimelimit=60s
    #     - --sim.timelimit=8m

    # # Consensus tests
    # - simulator: ethereum/consensus
    #   clients:
    #     - besu
    #     - erigon
    #     - ethereumjs
    #     - go-ethereum
    #     - nethermind
    #     - nimbus-el
    #     - reth
    #   extra_flags:
    #     - --client.checktimelimit=3m
    #     - --sim.parallelism=4
    #     #- --sim.timelimit=2h

    # # Consume Engine
    # - simulator: ethereum/eest-engine
    #   clients:
    #     - besu
    #     - erigon
    #     - ethereumjs
    #     - go-ethereum
    #     - nethermind
    #     - nimbus-el
    #     - reth
    #   extra_flags:
    #     - --client.checktimelimit=60s
    #     - --sim.parallelism=4
    #     - --client-file configs/prague.yaml
    #     #- --sim.timelimit=2h

    # # Consume RLP
    # - simulator: ethereum/eest-block-rlp
    #   clients:
    #     - besu
    #     - erigon
    #     - ethereumjs
    #     - go-ethereum
    #     - nethermind
    #     - nimbus-el
    #     - reth
    #   extra_flags:
    #     - --client.checktimelimit=60s
    #     - --sim.parallelism=4
    #     - --client-file configs/prague.yaml
    #     #- --sim.timelimit=2h
