- name: Add nimbusel user
  ansible.builtin.user:
    name: "{{ nimbusel_user }}"
  register: nimbusel_user_meta

- name: Create data dir
  ansible.builtin.file:
    path: "{{ nimbusel_datadir }}"
    state: directory
    mode: "0750"
    owner: "{{ nimbusel_user }}"
    group: "{{ nimbusel_user }}"

- name: Set permissions
  ansible.builtin.command: "chown -R {{ nimbusel_user }}:{{ nimbusel_user }} {{ nimbusel_datadir }}" # noqa no-free-form
  changed_when: false

- name: Run nimbusel container
  community.docker.docker_container:
    name: "{{ nimbusel_container_name }}"
    image: "{{ nimbusel_container_image }}"
    image_name_mismatch: recreate
    state: started
    restart_policy: always
    stop_timeout: "{{ nimbusel_container_stop_timeout }}"
    ports: "{{ nimbusel_container_ports }}"
    volumes: "{{ nimbusel_container_volumes }}"
    env: "{{ nimbusel_container_env }}"
    networks: "{{ nimbusel_container_networks }}"
    entrypoint: "{{ nimbusel_container_entrypoint | default(omit) }}"
    command: "{{ nimbusel_container_command + nimbusel_container_command_extra_args }}"
    user: "{{ nimbusel_user_meta.uid }}"
    pull: "{{ nimbusel_container_pull | bool }}"
    security_opts: "{{ nimbusel_container_security_opts }}"
