- name: Get user home dir
  ansible.builtin.user:
    name: "{{ oh_my_zsh_user }}"
    state: present
  check_mode: true
  register: oh_my_zsh_user_meta

- name: install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ oh_my_zsh_user_meta.home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    force: true

- name: install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: "{{ oh_my_zsh_user_meta.home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    force: true

- name: Set custom .zshrc config
  ansible.builtin.template:
    src: .zshrc.j2
    dest: "{{ oh_my_zsh_user_meta.home }}/.zshrc"
    mode: "0644"
    owner: "{{ oh_my_zsh_user }}"
    group: "{{ oh_my_zsh_user }}"
