nimbus_eth1_user: nimbus_eth1
nimbus_eth1_datadir: /data/nimbus_eth1
nimbus_eth1_auth_jwt_path: /data/execution-auth.secret
nimbus_eth1_announced_ip: "{{ ansible_host }}"
nimbus_eth1_announced_ipv6: "{{ ansible_default_ipv6.address if nimbus_eth1_ipv6_enabled and ansible_default_ipv6.address is defined else '' }}"

nimbus_eth1_cleanup: false # when set to "true" it will remove the container

nimbus_eth1_ports_p2p: 30303
nimbus_eth1_ports_http_rpc: 8545
nimbus_eth1_ports_engine: 8551
nimbus_eth1_ports_metrics: 6060

nimbus_eth1_ipv6_enabled: false

nimbus_eth1_container_name: nimbus_eth1
nimbus_eth1_container_image: ethpandaops/nimbus-eth1:master
nimbus_eth1_container_env: {}
nimbus_eth1_container_ports_ipv4:
  - "127.0.0.1:{{ nimbus_eth1_ports_http_rpc }}:{{ nimbus_eth1_ports_http_rpc }}"
  - "127.0.0.1:{{ nimbus_eth1_ports_engine }}:{{ nimbus_eth1_ports_engine }}"
  - "0.0.0.0:{{ nimbus_eth1_ports_p2p }}:{{ nimbus_eth1_ports_p2p }}"
  - "0.0.0.0:{{ nimbus_eth1_ports_p2p }}:{{ nimbus_eth1_ports_p2p }}/udp"

nimbus_eth1_container_ports_ipv6:
  - "[::]:{{ nimbus_eth1_ports_p2p }}:{{ nimbus_eth1_ports_p2p }}"
  - "[::]:{{ nimbus_eth1_ports_p2p }}:{{ nimbus_eth1_ports_p2p }}/udp"

nimbus_eth1_container_ports: >-
  {{ nimbus_eth1_container_ports_ipv4 + (nimbus_eth1_container_ports_ipv6 if nimbus_eth1_ipv6_enabled and ansible_default_ipv6.address is defined else []) }}

nimbus_eth1_container_volumes:
  - "{{ nimbus_eth1_datadir }}:/data"
  - "{{ nimbus_eth1_auth_jwt_path }}:/execution-auth.jwt:ro"
nimbus_eth1_container_security_opts: []
nimbus_eth1_container_stop_timeout: "300"
nimbus_eth1_container_networks: []
nimbus_eth1_container_command_default:
  - --log-level=INFO
  - --data-dir=/data
  - --http-port={{ nimbus_eth1_ports_http_rpc }}
  - --http.addr=0.0.0.0
  - --rpc
  - --rpc-api=eth,debug
  - --ws
  - --ws-api=eth,debug
  - --engine-api
  - --engine-api-address=0.0.0.0
  - --engine-api-port={{ nimbus_eth1_ports_engine }}
  - --jwt-secret=/execution-auth.jwt
  - --metrics
  - --metrics-address=0.0.0.0
  - --metrics-port={{ nimbus_eth1_ports_metrics }}
  - --nat=extip:{{ nimbus_eth1_announced_ip }}
  - --tcp-port={{ nimbus_eth1_ports_p2p }}

nimbus_eth1_container_command_v6: []
  # - --nat=extip:{{ nimbus_eth1_announced_ipv6 }} # not supported

nimbus_eth1_container_command: >-
  {{ nimbus_eth1_container_command_default + (nimbus_eth1_container_command_v6 if nimbus_eth1_ipv6_enabled and ansible_default_ipv6.address is defined else []) }}

nimbus_eth1_container_command_extra_args: []
#  - --rpc-api=eth,debug
#  - --http.vhosts=*

# Default image pull policy
nimbus_eth1_container_pull: false
