- name: Remove nimbus container
  community.docker.docker_container:
    name: "{{ nimbus_container_name }}"
    state: absent
  when: nimbus_cleanup or (not nimbus_enabled)

- name: Remove nimbus validator container
  community.docker.docker_container:
    name: "{{ nimbus_validator_container_name }}"
    state: absent
  when: nimbus_cleanup or nimbus_enabled
