- name: Setup otelcol
  ansible.builtin.import_tasks: setup.yaml
  when: not otelcol_contrib_cleanup

- name: Cleanup otelcol
  ansible.builtin.import_tasks: cleanup.yaml
  when: otelcol_contrib_cleanup
