- name: Create required directories
  ansible.builtin.file:
    path: "{{ otelcol_contrib_datadir }}"
    state: directory
    mode: "0755"

- name: Create otelcol config
  ansible.builtin.copy:
    content: "{{ otelcol_contrib_config }}"
    dest: "{{ otelcol_contrib_datadir }}/config.yaml"
    mode: '0644'
  notify: Restart otelcol container

- name: Run otelcol container
  community.docker.docker_container:
    name: "{{ otelcol_contrib_container_name }}"
    image: "{{ otelcol_contrib_container_image }}"
    image_name_mismatch: recreate
    command: "{{ otelcol_contrib_container_command }}"
    ports: "{{ otelcol_contrib_container_ports }}"
    restart_policy: "{{ otelcol_contrib_container_restart_policy }}"
    networks: "{{ otelcol_contrib_container_networks }}"
    volumes: "{{ otelcol_contrib_container_volumes }}"
    env: "{{ otelcol_contrib_container_env }}"
    user: "{{ otelcol_contrib_container_user }}"
