lodestar_enabled: true
lodestar_user: lodestar
lodestar_datadir: /data/lodestar
lodestar_auth_jwt_path: /data/execution-auth.secret
lodestar_execution_engine_endpoint: http://geth:8551
lodestar_beacon_endpoint: "http://{{ lodestar_container_name }}:{{ lodestar_ports_http_beacon }}"
lodestar_mev_boost_endpoint: "http://mev-boost:18550"

lodestar_announced_ip: "{{ ansible_host }}"
lodestar_announced_ipv6: "{{ ansible_default_ipv6.address if lodestar_ipv6_enabled and ansible_default_ipv6.address is defined else '' }}"

lodestar_cleanup: false # when set to "true" it will remove the container(s)

lodestar_ports_p2p_tcp: 9000
lodestar_ports_p2p_udp: 9000
lodestar_ports_p2p_udp_ipv6: 9002 # temporary until we have a fix for https://github.com/ChainSafe/lodestar/issues/6531#issuecomment-1995707028
lodestar_ports_p2p_tcp_ipv6: 9002
lodestar_ports_http_beacon: 9596
lodestar_ports_metrics: 8008

lodestar_ipv6_enabled: false
lodestar_supernode_enabled: false

lodestar_validator_enabled: false
lodestar_validator_fee_recipient: "0x25941dC771bB64514Fc8abBce970307Fb9d477e9" # theprotocolguild.eth
lodestar_validator_datadir: /data/lodestar-validator

################################################################################
##
## Beacon node container configuration
##
################################################################################
lodestar_container_name: lodestar
lodestar_container_image: chainsafe/lodestar:latest
lodestar_container_env: {}
lodestar_container_ports_ipv4:
  - "127.0.0.1:{{ lodestar_ports_http_beacon }}:{{ lodestar_ports_http_beacon }}"
  - "0.0.0.0:{{ lodestar_ports_p2p_tcp }}:{{ lodestar_ports_p2p_tcp }}"
  - "0.0.0.0:{{ lodestar_ports_p2p_udp }}:{{ lodestar_ports_p2p_udp }}/udp"

lodestar_container_ports_ipv6:
  - "[::]:{{ lodestar_ports_p2p_tcp_ipv6 }}:{{ lodestar_ports_p2p_tcp_ipv6 }}"
  - "[::]:{{ lodestar_ports_p2p_udp_ipv6 }}:{{ lodestar_ports_p2p_udp_ipv6 }}/udp"

lodestar_container_ports: >-
  {{ lodestar_container_ports_ipv4 + (lodestar_container_ports_ipv6 if lodestar_ipv6_enabled and ansible_default_ipv6.address is defined else []) }}

lodestar_container_volumes:
  - "{{ lodestar_datadir }}:/data"
  - "{{ lodestar_auth_jwt_path }}:/execution-auth.jwt:ro"
lodestar_container_security_opts: []
lodestar_container_stop_timeout: "300"
lodestar_container_networks: []
lodestar_container_command_default:
  - beacon
  - --dataDir=/data
  - --discv5
  - --listenAddress=0.0.0.0
  - --port={{ lodestar_ports_p2p_tcp }}
  - --enr.ip={{ lodestar_announced_ip }}
  - --enr.tcp={{ lodestar_ports_p2p_tcp }}
  - --enr.udp={{ lodestar_ports_p2p_udp }}
  - --discoveryPort6={{ lodestar_ports_p2p_udp_ipv6 }}
  - --rest
  - --rest.address=0.0.0.0
  - --rest.port={{ lodestar_ports_http_beacon }}
  - --jwt-secret=/execution-auth.jwt
  - --execution.urls={{ lodestar_execution_engine_endpoint }}
  - --metrics
  - --metrics.address=0.0.0.0
  - --metrics.port={{ lodestar_ports_metrics }}

lodestar_container_command_v6:
  - --listenAddress6=::0
  - --port6={{ lodestar_ports_p2p_tcp_ipv6 }}
  - --enr.ip6={{ lodestar_announced_ipv6 }}
  - --enr.tcp6={{ lodestar_ports_p2p_tcp_ipv6 }}
  - --enr.udp6={{ lodestar_ports_p2p_udp_ipv6 }}

lodestar_container_supernode_command:
  - --supernode

lodestar_container_command: >-
  {{
    lodestar_container_command_default +
    (lodestar_container_command_v6 if lodestar_ipv6_enabled and ansible_default_ipv6.address is defined else []) +
    (lodestar_container_supernode_command if lodestar_supernode_enabled else [])
  }}

lodestar_container_command_extra_args: []

checkpoint_sync_url: https://beaconstate.ethstaker.cc # noqa var-naming[no-role-prefix]
lodestar_checkpoint_sync_enabled: true
lodestar_container_command_checkpoint_args:
  - --checkpointSyncUrl={{ checkpoint_sync_url }}

################################################################################
##
## Validator container configuration
##
################################################################################
lodestar_validator_container_name: "{{ lodestar_container_name }}-validator"
lodestar_validator_container_image: "{{ lodestar_container_image }}"
lodestar_validator_container_env: {}
lodestar_validator_container_ports: []
lodestar_validator_container_volumes:
  - "{{ lodestar_validator_datadir }}:/validator-data"
lodestar_validator_container_security_opts: []
lodestar_validator_container_stop_timeout: "300"
lodestar_validator_container_networks: []
lodestar_validator_container_command:
  - validator
  - --dataDir=/validator-data
  - --keystoresDir=/validator-data/keys
  - --secretsDir=/validator-data/secrets
  - --beaconNodes={{ lodestar_beacon_endpoint }}
  - --suggestedFeeRecipient={{ lodestar_validator_fee_recipient }}

lodestar_validator_container_command_extra_args: []
  # - --builder
  # - --graffiti=hello-world

# Default image pull policy
lodestar_container_pull: false

################################################################################
##
## MEV Boost configuration
##
################################################################################
lodestar_mev_boost_enabled: false
lodestar_mev_boost_beacon_command:
  - --builder
  - --builder.urls={{ lodestar_mev_boost_endpoint }}
lodestar_mev_boost_validator_command:
  - --builder
