snapshot_fetcher_network: sepolia  # Network to fetch snapshot for (mainnet, sepolia, etc)
snapshot_fetcher_client: "{{ ethereum_node_el | default('geth') }}"  # Client to fetch snapshot for (geth, nethermind, etc)
snapshot_fetcher_out_dir: "/data/{{ snapshot_fetcher_client }}"  # Where to store the snapshot
snapshot_fetcher_base_url: "https://snapshots.ethpandaops.io"  # Base URL for snapshots
snapshot_fetcher_block: "latest"  # Block number to fetch, defaults to latest

snapshot_fetcher_s3_endpoint: "https://xxxxxx.r2.cloudflarestorage.com"
snapshot_fetcher_s3_access_key_id: "your-access-key-id"
snapshot_fetcher_s3_secret_access_key: "your-secret-access-key"
