- name: Add nginx-proxy user
  ansible.builtin.user:
    name: "{{ docker_nginx_proxy_user }}"
  register: docker_nginx_proxy_user_meta
- name: Get primary GID of nginx-proxy user
  ansible.builtin.command: id -g {{ docker_nginx_proxy_user }}
  register: docker_nginx_proxy_gid_cmd
  changed_when: false

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ docker_nginx_proxy_user }}"
    group: "{{ docker_nginx_proxy_user }}"
    mode: "0750"
  loop:
    - "{{ docker_nginx_proxy_datadir }}/conf"
    - "{{ docker_nginx_proxy_datadir }}/vhost"
    - "{{ docker_nginx_proxy_datadir }}/certs"
    - "{{ docker_nginx_proxy_datadir }}/acme"

- name: Add nginx config template
  ansible.builtin.copy:
    content: "{{ docker_nginx_proxy_conf_tmpl }}"
    dest: "{{ docker_nginx_proxy_datadir }}/nginx.tmpl"
    owner: "{{ docker_nginx_proxy_user }}"
    group: "{{ docker_nginx_proxy_user }}"
    mode: "0640"

- name: Add custom nginx config files
  ansible.builtin.copy:
    content: "{{ item.value }}"
    dest: "{{ docker_nginx_proxy_datadir }}/conf/{{ item.key }}"
    owner: "{{ docker_nginx_proxy_user }}"
    group: "{{ docker_nginx_proxy_user }}"
    mode: "0640"
  loop: "{{ docker_nginx_proxy_container_custom_config_files | dict2items }}"

- name: Add custom nginx vhost files
  ansible.builtin.copy:
    content: "{{ item.value }}"
    dest: "{{ docker_nginx_proxy_datadir }}/vhost/{{ item.key }}"
    owner: "{{ docker_nginx_proxy_user }}"
    group: "{{ docker_nginx_proxy_user }}"
    mode: "0640"
  loop: "{{ docker_nginx_proxy_container_custom_vhost_files | dict2items }}"


- name: Run nginx proxy container
  community.general.docker_container:
    name: "{{ docker_nginx_proxy_container_name }}"
    image: "{{ docker_nginx_proxy_container_image }}"
    image_name_mismatch: recreate
    published_ports: "{{ docker_nginx_proxy_container_published_ports }}"
    restart_policy: "{{ docker_nginx_proxy_container_restart_policy }}"
    networks: "{{ docker_nginx_proxy_container_networks }}"
    networks_cli_compatible: "{{ docker_nginx_proxy_container_networks_cli_compatible }}"
    network_mode: "{{ docker_nginx_proxy_container_network_mode }}"
    volumes: "{{ docker_nginx_proxy_container_volumes }}"
    env: "{{ docker_nginx_proxy_container_env }}"

- name: Run docker-gen container
  community.general.docker_container:
    name: "{{ docker_nginx_proxy_docker_gen_container_name }}"
    image: "{{ docker_nginx_proxy_docker_gen_container_image }}"
    image_name_mismatch: recreate
    platform: "{{ 'linux/arm/v7' if 'arm' in ansible_architecture else omit }}" # bug: There's no v8 arm image available
    command: "{{ docker_nginx_proxy_docker_gen_container_command }}"
    restart_policy: "{{ docker_nginx_proxy_docker_gen_container_restart_policy }}"
    networks: "{{ docker_nginx_proxy_acme_companion_container_networks }}"
    networks_cli_compatible: "{{ docker_nginx_proxy_docker_gen_container_networks_cli_compatible }}"
    network_mode: "{{ docker_nginx_proxy_docker_gen_container_network_mode }}"
    volumes: "{{ docker_nginx_proxy_docker_gen_container_volumes }}"
    env: "{{ docker_nginx_proxy_docker_gen_container_env }}"
    volumes_from: "{{ docker_nginx_proxy_docker_gen_container_volumes_from }}"

- name: Run acme companion container
  community.general.docker_container:
    name: "{{ docker_nginx_proxy_acme_companion_container_name }}"
    image: "{{ docker_nginx_proxy_acme_companion_container_image }}"
    image_name_mismatch: recreate
    platform: "{{ 'linux/arm/v7' if 'arm' in ansible_architecture else omit }}" # bug: There's no v8 arm image available
    restart_policy: "{{ docker_nginx_proxy_acme_companion_container_restart_policy }}"
    networks: "{{ docker_nginx_proxy_acme_companion_container_networks }}"
    networks_cli_compatible: "{{ docker_nginx_proxy_acme_companion_container_networks_cli_compatible }}"
    network_mode: "{{ docker_nginx_proxy_acme_companion_container_network_mode }}"
    volumes: "{{ docker_nginx_proxy_acme_companion_container_volumes }}"
    env: "{{ docker_nginx_proxy_acme_companion_container_env }}"
    volumes_from: "{{ docker_nginx_proxy_docker_gen_container_volumes_from }}"
  when: docker_nginx_proxy_acme_companion_enabled | bool

- name: Create ACME monitor script
  ansible.builtin.copy:
    src: acme-monitor.sh
    dest: "{{ docker_nginx_proxy_datadir }}/acme-monitor.sh"
    owner: "{{ docker_nginx_proxy_user }}"
    group: "{{ docker_nginx_proxy_user }}"
    mode: "0750"
  when: docker_nginx_proxy_acme_monitor_enabled

- name: Run ACME retry monitor sidecontainer
  community.general.docker_container:
    name: "{{ docker_nginx_proxy_acme_monitor_container_name }}"
    image: "{{ docker_nginx_proxy_acme_monitor_container_image }}"
    image_name_mismatch: recreate
    command: ["/acme-monitor.sh"]
    restart_policy: "{{ docker_nginx_proxy_acme_monitor_container_restart_policy }}"
    networks: "{{ docker_nginx_proxy_acme_monitor_container_networks }}"
    networks_cli_compatible: "{{ docker_nginx_proxy_acme_monitor_container_networks_cli_compatible }}"
    network_mode: "{{ docker_nginx_proxy_acme_monitor_container_network_mode }}"
    volumes: "{{ docker_nginx_proxy_acme_monitor_container_volumes + [docker_nginx_proxy_datadir + '/acme-monitor.sh:/acme-monitor.sh:ro'] }}"
    env: "{{ docker_nginx_proxy_acme_monitor_container_env }}"
  when: docker_nginx_proxy_acme_monitor_enabled

# --- wildcard: ensure templates dir
- name: Create docker-gen templates dir (wildcard)
  ansible.builtin.file:
    path: "{{ docker_nginx_proxy_templates_dir }}"
    state: directory
    owner: "{{ docker_nginx_proxy_user }}"
    group: "{{ docker_nginx_proxy_user }}"
    mode: "0750"
  when: docker_nginx_proxy_wildcard_enabled | bool

# --- wildcard: install symlink template
- name: Create wildcard symlink template
  ansible.builtin.copy:
    src: wildcard-symlinks.tmpl
    dest: "{{ docker_nginx_proxy_templates_dir }}/wildcard-symlinks.tmpl"
    owner: "{{ docker_nginx_proxy_user }}"
    group: "{{ docker_nginx_proxy_user }}"
    mode: "0644"
  when: docker_nginx_proxy_wildcard_enabled | bool

- name: Create certificate loader script
  ansible.builtin.copy:
    src: cert-loader.sh
    dest: "{{ docker_nginx_proxy_datadir }}/cert-loader.sh"
    owner: "{{ docker_nginx_proxy_user }}"
    group: "{{ docker_nginx_proxy_user }}"
    mode: "0750"
  when: docker_nginx_proxy_wildcard_enabled | bool

# --- wildcard: certificate loader to pull bundle and reload proxy
- name: Run certificate loader sidecar
  community.general.docker_container:
    name: "{{ docker_nginx_proxy_cert_loader_container_name }}"
    image: "{{ docker_nginx_proxy_cert_loader_container_image }}"
    image_name_mismatch: recreate
    restart_policy: "{{ docker_nginx_proxy_cert_loader_container_restart_policy }}"
    networks: "{{ docker_nginx_proxy_cert_loader_container_networks }}"
    network_mode: "{{ docker_nginx_proxy_cert_loader_container_network_mode }}"
    volumes: "{{ docker_nginx_proxy_cert_loader_container_volumes }}"
    volumes_from: "{{ docker_nginx_proxy_cert_loader_container_volumes_from }}"
    env: "{{ docker_nginx_proxy_cert_loader_container_env }}"
    command: "{{ docker_nginx_proxy_cert_loader_container_command }}"
  when: docker_nginx_proxy_wildcard_enabled | bool

# --- wildcard: docker-gen watcher to create per-vhost symlinks & HUP nginx-proxy
- name: Run docker-gen symlinker for wildcard cert
  community.general.docker_container:
    name: "{{ docker_nginx_proxy_cert_linker_container_name }}"
    image: "{{ docker_nginx_proxy_cert_linker_container_image }}"
    image_name_mismatch: recreate
    restart_policy: "{{ docker_nginx_proxy_cert_linker_container_restart_policy }}"
    networks: "{{ docker_nginx_proxy_cert_linker_container_networks }}"
    network_mode: "{{ docker_nginx_proxy_cert_linker_container_network_mode }}"
    volumes_from: "{{ docker_nginx_proxy_cert_linker_container_volumes_from }}"
    volumes: "{{ docker_nginx_proxy_cert_linker_container_volumes }}"
    env: "{{ docker_nginx_proxy_cert_linker_container_env }}"
    command: "{{ docker_nginx_proxy_cert_linker_container_command }}"
  when: docker_nginx_proxy_wildcard_enabled | bool