xatu_sentry_cleanup: false

xatu_sentry_user: "xatu-sentry"

xatu_sentry_container_name: "xatu-sentry"
xatu_sentry_container_image: "ethpandaops/xatu:latest"
xatu_sentry_container_env: {}
xatu_sentry_container_ports: []
xatu_sentry_container_volumes:
  - "{{ xatu_sentry_paths_config }}/config.yaml:/config.yaml:ro"

xatu_sentry_container_stop_timeout: "120"
xatu_sentry_container_networks: []

xatu_sentry_paths_config: /etc/xatu-sentry/

xatu_sentry_container_command:
  - sentry
  - --config=/config.yaml

xatu_sentry_config_name: "{{ inventory_hostname }}"
xatu_sentry_config_beacon_uri: your-beacon-node:4000
xatu_sentry_config_server_address: remote-xatu-server:1234
xatu_sentry_config_server_tls_enabled: true
xatu_sentry_config_server_auth_user: xatu-user
xatu_sentry_config_server_auth_password: xatu-password
xatu_sentry_config_network_name_override: ""

xatu_sentry_config: |
  logging: "info"
  metricsAddr: ":9090"
  name: "{{ xatu_sentry_config_name }}"
  ethereum:
    beaconNodeAddress: {{ xatu_sentry_config_beacon_uri }}
    overrideNetworkName: {{ xatu_sentry_config_network_name_override }}
  outputs:
  - name: grpc
    type: xatu
    config:
      address: {{ xatu_sentry_config_server_address }}
      tls: {{ xatu_sentry_config_server_tls_enabled }}
      headers:
        authorization: "Basic {{ (xatu_sentry_config_server_auth_user + ":" + xatu_sentry_config_server_auth_password) | b64encode }}"
