- name: Remove prysm container
  community.docker.docker_container:
    name: "{{ prysm_container_name }}"
    state: absent
  when: prysm_cleanup or (not prysm_enabled)

- name: Remove prysm validator container
  community.docker.docker_container:
    name: "{{ prysm_validator_container_name }}"
    state: absent
  when: prysm_cleanup or (not prysm_validator_enabled)
