- name: "Run genesis generation"
  vars:
    ansible_connection: local
  delegate_to: 127.0.0.1
  run_once: true
  become: false
  block:
    - name: Create temporary config directory
      ansible.builtin.tempfile:
        state: directory
        suffix: ethereum-genesis-config-input
      register: ethereum_genesis_generator_tmp_config_dir_register

    - name: Create temporary output directory
      ansible.builtin.tempfile:
        state: directory
        suffix: ethereum-genesis-config-output
      register: ethereum_genesis_generator_tmp_output_dir_register

    - name: Create config file directories
      ansible.builtin.file:
        path: "{{ ethereum_genesis_generator_tmp_config_dir_register.path }}/{{ item.key | dirname }}"
        state: directory
        mode: '0755'
      loop: "{{ ethereum_genesis_generator_config_files | dict2items }}"

    - name: Copy config files
      ansible.builtin.copy:
        content: "{{ item.value }}"
        dest: "{{ ethereum_genesis_generator_tmp_config_dir_register.path }}/{{ item.key }}"
        mode: "0644"
      loop: "{{ ethereum_genesis_generator_config_files | dict2items }}"

    - name: Check if Docker is rootless
      ansible.builtin.command: docker info -f '{{ "{{json .SecurityOptions}}" }}'
      register: docker_secopts
      changed_when: false

    - name: Set rootless fact
      ansible.builtin.set_fact:
        docker_is_rootless: "{{ 'name=rootless' in docker_secopts.stdout }}"

    - name: Compute docker user flag
      ansible.builtin.set_fact:
        docker_user_flag: "{{ docker_is_rootless | ternary('', '-u ' ~ (ansible_effective_user_id | default(ansible_uid, true))) }}"

    - name: Run genesis generator
      ansible.builtin.shell: >
        docker run --rm -t {{ docker_user_flag }}
        -v {{ ethereum_genesis_generator_tmp_output_dir_register.path }}:/data
        -v {{ ethereum_genesis_generator_tmp_config_dir_register.path }}:/config
        {{ ethereum_genesis_generator_container_image }} all
      register: ethereum_genesis_generator_cmd
      changed_when: false
      failed_when: (ethereum_genesis_generator_cmd.rc != 0) or (ethereum_genesis_generator_cmd.stdout == "")

    - name: Removes extended attr from config.yaml, breaks on linux due to perms if present
      ansible.builtin.command: xattr -c "{{ ethereum_genesis_generator_tmp_output_dir_register.path }}/metadata/config.yaml"
      changed_when: true
      when: ansible_os_family == "Darwin"

    - name: Set config.yaml to the right permissions post attribute change
      ansible.builtin.file:
        path: "{{ ethereum_genesis_generator_tmp_output_dir_register.path }}/metadata/config.yaml"
        mode: '0644'
      when: ansible_os_family == "Darwin"

    - name: Create final output directory
      ansible.builtin.file:
        path: "{{ ethereum_genesis_generator_output_dir }}"
        state: directory
        mode: '0755'

    - name: Create final output directory
      ansible.builtin.file:
        path: "{{ ethereum_genesis_generator_output_dir }}/metadata"
        state: directory
        mode: '0755'

    - name: Create final output directory
      ansible.builtin.file:
        path: "{{ ethereum_genesis_generator_output_dir }}/parsed"
        state: directory
        mode: '0755'

    - name: Move tmp output to final output dir
      ansible.builtin.shell: >
        mv {{ ethereum_genesis_generator_tmp_output_dir_register.path }}/metadata/* {{ ethereum_genesis_generator_output_dir }}/metadata/
      changed_when: true

    - name: Move tmp output to final output dir
      ansible.builtin.shell: >
        mv {{ ethereum_genesis_generator_tmp_output_dir_register.path }}/parsed/* {{ ethereum_genesis_generator_output_dir }}/parsed/
      changed_when: true

    - name: Cleanup tmp dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ ethereum_genesis_generator_tmp_config_dir_register.path }}"
        - "{{ ethereum_genesis_generator_tmp_output_dir_register.path }}"

    - name: Info
      ansible.builtin.debug:
        msg: "Genesis configs can be found in the following directory: {{ ethereum_genesis_generator_output_dir }}"
  always:
    - name: Inform of failure
      ansible.builtin.debug:
        msg: |
          Something went wrong. Some useful information that can be used to debug the problem:
          - Temp config dir: {{ ethereum_genesis_generator_tmp_config_dir_register.path }}
          - Temp output dir: {{ ethereum_genesis_generator_tmp_output_dir_register.path }}
      when: >-
        (ethereum_genesis_generator_cmd.rc | default('')  != 0)
