---
- name: Ensure iptables is installed.
  ansible.builtin.package:
    name: iptables
    state: present

- name: Copy firewall script into place.
  ansible.builtin.template:
    src: firewall.bash.j2
    dest: /etc/firewall.bash
    owner: root
    group: root
    mode: "0744"
  notify: Restart firewall

- name: Copy firewall systemd unit file into place (for systemd systems).
  ansible.builtin.template:
    src: firewall.unit.j2
    dest: /etc/systemd/system/firewall.service
    owner: root
    group: root
    mode: "0755"
  when: >
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version.split(".")[0]|int >= 16) or
    (ansible_distribution == 'Debian' and ansible_distribution_version.split(".")[0]|int >= 8) or
    (ansible_distribution == 'CentOS' and ansible_distribution_version.split(".")[0]|int >= 7) or
    (ansible_distribution == 'Fedora')

- name: Ensure the firewall is enabled and will start on boot.
  ansible.builtin.service:
    name: firewall
    state: started
    enabled: true
