- name: "Run post network setup tasks"
  vars:
    ansible_connection: local
  delegate_to: 127.0.0.1
  run_once: true
  become: false
  block:
    - name: Make sure output dir exists
      ansible.builtin.file:
        path: "{{ ethereum_genesis_generator_output_dir }}/metadata"
        state: directory
        recurse: true
    - name: Generate parsed dir exists
      ansible.builtin.file:
        path: "{{ ethereum_genesis_generator_output_dir }}/parsed"
        state: directory
        recurse: true
    # Generate missing network config files
    - name: Generate enodes.txt for EL clients
      ansible.builtin.copy:
        content: |-
          {% for host in (groups['ethereum_node'] | sort | unique)[:20] -%}
          {% if hostvars[host]['ethereum_node_fact_el_enode'] is defined %}
          {{ hostvars[host]['ethereum_node_fact_el_enode'] }}
          {%- if not loop.last %}

          {% endif %}
          {% endif %}
          {% endfor %}
        dest: "{{ ethereum_genesis_generator_output_dir }}/metadata/enodes.txt"
        mode: "0644"
    - name: Generate "bootstrap_nodes.txt" for CL clients
      ansible.builtin.copy:
        content: |-
          {% for host in ((groups['ethereum_node'] + groups['bootnode']) | sort | unique)[:20] -%}
          {% if hostvars[host]['cl_bootnode_fact_enr'] is defined %}
          {{ hostvars[host]['cl_bootnode_fact_enr'] }}
          {%- if not loop.last %}

          {% endif %}
          {% endif %}
          {% if hostvars[host]['ethereum_node_fact_cl_enr'] is defined %}
          {{ hostvars[host]['ethereum_node_fact_cl_enr'] }}
          {%- if not loop.last %}

          {% endif %}
          {% endif %}
          {% endfor %}
        dest: "{{ ethereum_genesis_generator_output_dir }}/metadata/bootstrap_nodes.txt"
        mode: "0644"
    - name: Generate "bootstrap_nodes.yaml" for Prysm
      ansible.builtin.copy:
        content: |-
          {% for host in ((groups['ethereum_node'] + groups['bootnode']) | sort | unique)[:20] -%}
          {% if hostvars[host]['cl_bootnode_fact_enr'] is defined %}
          - {{ hostvars[host]['cl_bootnode_fact_enr'] }}
          {%- if not loop.last %}

          {% endif %}
          {% endif %}
          {% if hostvars[host]['ethereum_node_fact_cl_enr'] is defined %}
          - {{ hostvars[host]['ethereum_node_fact_cl_enr'] }}
          {%- if not loop.last %}

          {% endif %}
          {% endif %}
          {% endfor %}
        dest: "{{ ethereum_genesis_generator_output_dir }}/metadata/bootstrap_nodes.yaml"
        mode: "0644"
