- name: Add geth user
  ansible.builtin.user:
    name: "{{ geth_user }}"
  register: geth_user_meta

- name: Create data dir
  ansible.builtin.file:
    path: "{{ geth_datadir }}"
    state: directory
    mode: "0750"
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"

- name: Set permissions
  ansible.builtin.command: "chown -R {{ geth_user }}:{{ geth_user }} {{ geth_datadir }}" # noqa no-free-form
  failed_when: false
  changed_when: false

- name: Run geth container
  community.docker.docker_container:
    name: "{{ geth_container_name }}"
    image: "{{ geth_container_image }}"
    image_name_mismatch: recreate
    state: started
    restart_policy: always
    stop_timeout: "{{ geth_container_stop_timeout }}"
    ports: "{{ geth_container_ports }}"
    volumes: "{{ geth_container_volumes }}"
    env: "{{ geth_container_env }}"
    networks: "{{ geth_container_networks }}"
    entrypoint: "{{ geth_container_entrypoint | default(omit) }}"
    command: "{{ geth_container_command + geth_container_command_extra_args }}"
    user: "{{ geth_user_meta.uid }}"
    pull: "{{ geth_container_pull | bool }}"
    security_opts: "{{ geth_container_security_opts }}"
