---
mev_relay_cleanup_all: false

mev_relay_user: mev_relay
mev_relay_datadir: "/data/mev_relay"
mev_relay_docker_network_name: shared
mev_relay_docker_networks:
  - name: "{{ mev_relay_docker_network_name }}"

# ------------------------------------------------------------------
# mev-relay ports
mev_relay_database_port: 5432
mev_relay_redis_port: 6379
mev_relay_website_listening_port: 9060
mev_relay_api_listening_port: 9062

# mev-relay-database
mev_relay_db_enabled: true
mev_relay_db_datadir: "{{ mev_relay_datadir }}/mev-relay-database"
mev_relay_db_container_name: mev-relay-database
mev_relay_db_container_image: bitnami/postgresql:15
mev_relay_db_container_env:
  POSTGRESQL_USERNAME: postgres
  POSTGRESQL_PASSWORD: postgres
  POSTGRESQL_DATABASE: boostrelay
mev_relay_db_container_ports:
  - "127.0.0.1:{{ mev_relay_database_port }}:{{ mev_relay_database_port }}"
mev_relay_db_container_volumes:
  - "{{ mev_relay_datadir }}:/bitnami/postgresql"
mev_relay_db_container_stop_timeout: "300"
mev_relay_db_container_pull: false
mev_relay_db_container_networks: "{{ mev_relay_docker_networks }}"

# ------------------------------------------------------------------
# mev-relay-redis
mev_relay_redis_enabled: true
mev_relay_redis_datadir: "{{ mev_relay_datadir }}/mev-relay-redis"
mev_relay_redis_container_name: mev-relay-redis
mev_relay_redis_container_image: bitnami/redis:6.2.12
mev_relay_redis_container_env:
  ALLOW_EMPTY_PASSWORD=yes
mev_relay_redis_container_ports:
  - "127.0.0.1:{{ mev_relay_redis_port }}:{{ mev_relay_redis_port }}"
mev_relay_redis_container_volumes:
  - "{{ mev_relay_datadir }}:/bitnami/redis/data"
mev_relay_redis_container_stop_timeout: "300"
mev_relay_redis_container_pull: false
mev_relay_redis_container_networks: "{{ mev_relay_docker_networks }}"

# ------------------------------------------------------------------
# mev-relay-housekeeper
mev_relay_housekeeper_enabled: true
mev_relay_housekeeper_datadir: "{{ mev_relay_datadir }}/mev-relay-housekeeper"
mev_relay_housekeeper_container_name: mev-relay-housekeeper
mev_relay_housekeeper_container_image: flashbots/mev-boost-relay:latest
mev_relay_housekeeper_container_env: {}
mev_relay_housekeeper_container_ports: []
mev_relay_housekeeper_container_volumes: []
mev_relay_housekeeper_container_stop_timeout: "300"
mev_relay_housekeeper_container_pull: false
mev_relay_housekeeper_container_networks: "{{ mev_relay_docker_networks }}"
mev_relay_housekeeper_container_command:
  - housekeeper
mev_relay_housekeeper_container_command_extra_args: []

# ------------------------------------------------------------------
# mev-relay-api
mev_relay_api_enabled: true
mev_relay_api_datadir: "{{ mev_relay_datadir }}/mev-relay-api"
mev_relay_api_container_name: mev-relay-api
mev_relay_api_container_image: flashbots/mev-boost-relay:latest
mev_relay_api_container_env: {}
mev_relay_api_container_ports:
  - "127.0.0.1:{{ mev_relay_api_listening_port }}:{{ mev_relay_api_listening_port }}"
mev_relay_api_container_volumes: []
mev_relay_api_container_stop_timeout: "300"
mev_relay_api_container_pull: false
mev_relay_api_container_networks: "{{ mev_relay_docker_networks }}"
mev_relay_api_container_command:
  - api
mev_relay_api_container_command_extra_args: []

# ------------------------------------------------------------------
# mev-relay-website
mev_relay_website_enabled: true
mev_relay_website_datadir: "{{ mev_relay_datadir }}/mev-relay-website"
mev_relay_website_container_name: mev-relay-website
mev_relay_website_container_image: flashbots/mev-boost-relay:latest
mev_relay_website_container_env: {}
mev_relay_website_container_ports:
  - "127.0.0.1:{{ mev_relay_website_listening_port }}:{{ mev_relay_website_listening_port }}"
mev_relay_website_container_volumes: []
mev_relay_website_container_stop_timeout: "300"
mev_relay_website_container_pull: false
mev_relay_website_container_networks: "{{ mev_relay_docker_networks }}"
mev_relay_website_container_command:
  - website
mev_relay_website_container_command_extra_args: []
