- name: Prepare
  hosts: molecule
  become: true
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  tasks:
    - name: Main block
      block:
        - name: Install docker
          ansible.builtin.import_role:
            name: geerlingguy.docker
        - name: Install pip and docker pkg
          ansible.builtin.import_role:
            name: geerlingguy.pip
          vars:
            pip_install_packages:
              - name: docker
                extra_args: --break-system-packages
        - name: Install golang
          ansible.builtin.import_role:
            name: gantsign.golang
          vars:
            golang_gopath: '/data/workspace-go'
            golang_version: '1.24.13'
            golang_redis_sha256sum: 1fc94b57134d51669c72173ad5d49fd62afb0f1db9bf3f798fd98ee423f8d730
            golang_mirror: https://go.dev/dl
