#
# Copy over custom network config directory
#

- name: Check if rsync is installed
  ansible.builtin.package:
    name: rsync
    state: present

# Option A: Allow cloning from git
- name: Git checkout config
  ansible.builtin.git:
    repo: "{{ eth_testnet_config_git_repo }}"
    dest: "{{ eth_testnet_temp_config_dir }}"
    version: "{{ eth_testnet_config_git_version }}"
    update: true
    force: true
  when: eth_testnet_config_git_enabled

- name: Create dest dir
  ansible.builtin.file:
    path: "{{ eth_testnet_config_dir }}"
    state: directory
    recurse: true
  when: eth_testnet_config_git_enabled

- name: Synchronize two directories on one remote host.
  ansible.posix.synchronize:
    src: "{{ eth_testnet_temp_config_dir }}/{{ eth_testnet_path_in_temp_git_repo }}"
    dest: "{{ eth_testnet_config_dir }}"
  delegate_to: "{{ inventory_hostname }}"
  when: eth_testnet_config_git_enabled

- name: Recursively remove directory
  ansible.builtin.file:
    path: "{{ eth_testnet_temp_config_dir }}"
    state: absent
  when: eth_testnet_config_git_enabled

# Option B: Allow copying over local dir
- name: Create dest dir
  ansible.builtin.file:
    path: "{{ eth_testnet_config_dir }}"
    state: directory
    recurse: true
  when: eth_testnet_config_local_dir_enabled

- name: Copy local config dir
  ansible.posix.synchronize:
    src: "{{ eth_testnet_config_local_dir_src }}"
    dest: "{{ eth_testnet_config_dir }}/"
  when: eth_testnet_config_local_dir_enabled

# Option C: Download and extract tarball
- name: Create dest dir for tarball
  ansible.builtin.file:
    path: "{{ eth_testnet_config_dir }}"
    state: directory
    recurse: true
  when: eth_testnet_config_tarball_enabled

- name: Download tarball
  ansible.builtin.get_url:
    url: "{{ eth_testnet_config_tarball_url }}"
    dest: "/tmp/eth_testnet_config.tar.gz"
    mode: '0644'
  when: eth_testnet_config_tarball_enabled

- name: Extract tarball
  ansible.builtin.unarchive:
    src: "/tmp/eth_testnet_config.tar.gz"
    dest: "{{ eth_testnet_config_dir }}"
    remote_src: true
  when: eth_testnet_config_tarball_enabled

- name: Clean up tarball
  ansible.builtin.file:
    path: "/tmp/eth_testnet_config.tar.gz"
    state: absent
  when: eth_testnet_config_tarball_enabled
