- name: Create dir for IP names file
  ansible.builtin.file:
    path: "{{ bootnodoor_ip_names_host_file | dirname }}"
    state: directory
    mode: "0755"
  when: bootnodoor_ip_names_enabled

- name: Upload IP names file for the web UI
  ansible.builtin.copy:
    src: "{{ bootnodoor_ip_names_src }}"
    dest: "{{ bootnodoor_ip_names_host_file }}"
    mode: "0644"
  when: bootnodoor_ip_names_enabled

- name: Run bootnodoor container
  community.docker.docker_container:
    name: "{{ bootnodoor_container_name }}"
    image: "{{ bootnodoor_container_image }}"
    image_name_mismatch: recreate
    state: started
    restart_policy: always
    stop_timeout: "{{ bootnodoor_container_stop_timeout }}"
    ports: "{{ bootnodoor_container_ports }}"
    volumes: "{{ bootnodoor_container_volumes }}"
    env: "{{ bootnodoor_container_env }}"
    networks: "{{ bootnodoor_container_networks }}"
    command: "{{ bootnodoor_container_command }}"

- name: Set facts
  ansible.builtin.import_tasks: facts.yaml
  when: bootnodoor_set_facts
  tags:
    - ethereum_node_fact_discovery
    - bootnodoor_fact_discovery
