- name: Remove lodestar container
  community.docker.docker_container:
    name: "{{ lodestar_container_name }}"
    state: absent
  when: lodestar_cleanup or (not lodestar_enabled)

- name: Remove lodestar validator container
  community.docker.docker_container:
    name: "{{ lodestar_validator_container_name }}"
    state: absent
  when: lodestar_cleanup or (not lodestar_validator_enabled)
