chaosd_version: "v1.4.0"
chaosd_download_url: "https://mirrors.chaos-mesh.org/chaosd-{{ chaosd_version }}-linux-amd64.tar.gz"
chaosd_sha256: "auto_fill_sha256_here"
chaosd_port: 31767
chaosd_install_dir: /opt/chaosd
chaosd_iface: eth0          # primary NIC used by your droplets
