- name: Remove xatu stack containers
  community.docker.docker_compose_v2:
    project_src: "{{ xatu_stack_repo_path }}"
    files:
      - docker-compose.yml
    state: absent
    remove_volumes: true

- name: Remove xatu stack repository
  ansible.builtin.file:
    path: "{{ xatu_stack_repo_path }}"
    state: absent

- name: Remove xatu stack user
  ansible.builtin.user:
    name: "{{ xatu_stack_user }}"
    state: absent
    remove: true

- name: Remove xatu stack directories
  ansible.builtin.file:
    path: "{{ xatu_stack_paths_config }}"
    state: absent
