all:
  children:
    molecule:
      hosts:
        blockscout:
          ansible_connection: containers.podman.podman
          container_image: docker.io/geerlingguy/docker-debian12-ansible:latest
          container_command: ""
          container_privileged: true
          container_systemd: true
          container_volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:rw
