- name: Stop and disable chaosd service
  ansible.builtin.systemd:
    name: chaosd
    enabled: false
    state: stopped
  ignore_errors: true

- name: Remove systemd service file
  ansible.builtin.file:
    path: /etc/systemd/system/chaosd.service
    state: absent
  notify: Reload systemd

- name: Remove chaosd installation directory
  ansible.builtin.file:
    path: "{{ chaosd_install_dir }}"
    state: absent

- name: Clean up temporary files
  ansible.builtin.file:
    path: /tmp/chaosd.tar.gz
    state: absent

- name: Cleanup nginx proxy for chaosd
  ansible.builtin.include_tasks:
    file: cleanup_nginx_proxy.yaml
  when: chaosd_nginx_proxy_enabled | bool