- name: Stop traffic control service
  ansible.builtin.systemd:
    name: "{{ traffic_control_service_name }}"
    state: stopped

- name: Disable traffic control service
  ansible.builtin.systemd:
    name: "{{ traffic_control_service_name }}"
    enabled: false
    state: absent

- name: Remove traffic control scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ traffic_control_script_path_up }}"
    - "{{ traffic_control_script_path_down }}"
