- name: Install dependencies
  ansible.builtin.package:
    name: "{{ 'iproute2' if ansible_os_family == 'Debian' else 'iproute' }}"
    state: present

- name: Create script
  ansible.builtin.template:
    src: apply_traffic_control.sh.j2
    dest: "{{ traffic_control_script_path }}"
    mode: '0740'
  notify: Restart traffic control service

- name: Create systemd service file
  ansible.builtin.template:
    src: traffic-control.service.j2
    dest: "/etc/systemd/system/{{ traffic_control_service_name }}"
    mode: '0640'
  register: traffic_control_systemd_file
  notify: Restart traffic control service

- name: Enable and start service
  ansible.builtin.systemd:
    name: "{{ traffic_control_service_name }}"
    enabled: true
    state: started
    daemon_reload: true
