- name: "Execution client: besu"
  when: ethereum_node_el == "besu"
  ansible.builtin.include_role:
    name: ethpandaops.general.besu
  vars:
    besu_announced_ip: "{{ ethereum_node_announced_ip }}"
    besu_ports_p2p: "{{ ethereum_node_el_ports_p2p_tcp }}"
    besu_ports_http_rpc: "{{ ethereum_node_el_ports_http_rpc }}"
    besu_ports_engine: "{{ ethereum_node_el_ports_engine }}"
    besu_ports_metrics: "{{ ethereum_node_el_ports_metrics }}"
    besu_container_networks: "{{ ethereum_node_docker_networks }}"
    besu_container_pull: "{{ ethereum_node_images_always_pull }}"
    besu_ipv6_enabled: "{{ ethereum_node_ipv6_enabled }}"

- name: "Execution client: geth"
  when: ethereum_node_el == "geth"
  ansible.builtin.include_role:
    name: ethpandaops.general.geth
  vars:
    geth_announced_ip: "{{ ethereum_node_announced_ip }}"
    geth_ports_p2p: "{{ ethereum_node_el_ports_p2p_tcp }}"
    geth_ports_http_rpc: "{{ ethereum_node_el_ports_http_rpc }}"
    geth_ports_engine: "{{ ethereum_node_el_ports_engine }}"
    geth_ports_metrics: "{{ ethereum_node_el_ports_metrics }}"
    geth_container_networks: "{{ ethereum_node_docker_networks }}"
    geth_container_pull: "{{ ethereum_node_images_always_pull }}"
    geth_ipv6_enabled: "{{ ethereum_node_ipv6_enabled }}"

- name: "Execution client: erigon"
  when: ethereum_node_el == "erigon"
  ansible.builtin.include_role:
    name: ethpandaops.general.erigon
  vars:
    erigon_announced_ip: "{{ ethereum_node_announced_ip }}"
    erigon_ports_p2p: "{{ ethereum_node_el_ports_p2p_tcp }}"
    erigon_ports_http_rpc: "{{ ethereum_node_el_ports_http_rpc }}"
    erigon_ports_engine: "{{ ethereum_node_el_ports_engine }}"
    erigon_ports_metrics: "{{ ethereum_node_el_ports_metrics }}"
    erigon_container_networks: "{{ ethereum_node_docker_networks }}"
    erigon_container_pull: "{{ ethereum_node_images_always_pull }}"
    erigon_ipv6_enabled: "{{ ethereum_node_ipv6_enabled }}"

- name: "Execution client: nethermind"
  when: ethereum_node_el == "nethermind"
  ansible.builtin.include_role:
    name: ethpandaops.general.nethermind
  vars:
    nethermind_announced_ip: "{{ ethereum_node_announced_ip }}"
    nethermind_ports_p2p: "{{ ethereum_node_el_ports_p2p_tcp }}"
    nethermind_ports_http_rpc: "{{ ethereum_node_el_ports_http_rpc }}"
    nethermind_ports_engine: "{{ ethereum_node_el_ports_engine }}"
    nethermind_ports_metrics: "{{ ethereum_node_el_ports_metrics }}"
    nethermind_container_networks: "{{ ethereum_node_docker_networks }}"
    nethermind_container_pull: "{{ ethereum_node_images_always_pull }}"
    nethermind_ipv6_enabled: "{{ ethereum_node_ipv6_enabled }}"

- name: "Execution client: ethereumjs"
  when: ethereum_node_el == "ethereumjs"
  ansible.builtin.include_role:
    name: ethpandaops.general.ethereumjs
  vars:
    ethereumjs_announced_ip: "{{ ethereum_node_announced_ip }}"
    ethereumjs_ports_p2p: "{{ ethereum_node_el_ports_p2p_tcp }}"
    ethereumjs_ports_http_rpc: "{{ ethereum_node_el_ports_http_rpc }}"
    ethereumjs_ports_engine: "{{ ethereum_node_el_ports_engine }}"
    ethereumjs_container_networks: "{{ ethereum_node_docker_networks }}"
    ethereumjs_container_pull: "{{ ethereum_node_images_always_pull }}"
    ethereumjs_ipv6_enabled: "{{ ethereum_node_ipv6_enabled }}"

- name: "Execution client: reth"
  when: ethereum_node_el == "reth"
  ansible.builtin.include_role:
    name: ethpandaops.general.reth
  vars:
    reth_announced_ip: "{{ ethereum_node_announced_ip }}"
    reth_ports_p2p: "{{ ethereum_node_el_ports_p2p_tcp }}"
    reth_ports_http_rpc: "{{ ethereum_node_el_ports_http_rpc }}"
    reth_ports_engine: "{{ ethereum_node_el_ports_engine }}"
    reth_container_networks: "{{ ethereum_node_docker_networks }}"
    reth_container_pull: "{{ ethereum_node_images_always_pull }}"
    reth_ipv6_enabled: "{{ ethereum_node_ipv6_enabled }}"

- name: "Execution client: nimbusel"
  when: ethereum_node_el == "nimbusel"
  ansible.builtin.include_role:
    name: ethpandaops.general.nimbusel
  vars:
    nimbusel_announced_ip: "{{ ethereum_node_announced_ip }}"
    nimbusel_ports_p2p: "{{ ethereum_node_el_ports_p2p_tcp }}"
    nimbusel_ports_http_rpc: "{{ ethereum_node_el_ports_http_rpc }}"
    nimbusel_ports_engine: "{{ ethereum_node_el_ports_engine }}"
    nimbusel_ports_metrics: "{{ ethereum_node_el_ports_metrics }}"
    nimbusel_container_networks: "{{ ethereum_node_docker_networks }}"
    nimbusel_container_pull: "{{ ethereum_node_images_always_pull }}"
    nimbusel_ipv6_enabled: "{{ ethereum_node_ipv6_enabled }}"
