- name: Set execution client vars
  ansible.builtin.set_fact:
    ethereum_node_dynamic_el_vars:
      "{{ ethereum_node_el }}_announced_ip": "{{ ethereum_node_announced_ip }}"
      "{{ ethereum_node_el }}_ports_p2p": "{{ ethereum_node_el_ports_p2p_tcp }}"
      "{{ ethereum_node_el }}_ports_http_rpc": "{{ ethereum_node_el_ports_http_rpc }}"
      "{{ ethereum_node_el }}_ports_engine": "{{ ethereum_node_el_ports_engine }}"
      "{{ ethereum_node_el }}_ports_metrics": "{{ ethereum_node_el_ports_metrics }}"
      "{{ ethereum_node_el }}_container_networks": "{{ ethereum_node_docker_networks }}"
      "{{ ethereum_node_el }}_container_pull": "{{ ethereum_node_images_always_pull }}"
      "{{ ethereum_node_el }}_ipv6_enabled": "{{ ethereum_node_ipv6_enabled }}"

- name: "Setup execution client: {{ ethereum_node_el }}"
  ansible.builtin.include_role:
    name: "ethpandaops.general.{{ ethereum_node_el }}"
  vars: "{{ ethereum_node_dynamic_el_vars }}"
