- name: Set consensus client variables
  ansible.builtin.set_fact:
    ethereum_node_dynamic_cl_vars:
      "{{ ethereum_node_cl }}_announced_ip": "{{ ethereum_node_announced_ip }}"
      "{{ ethereum_node_cl }}_ports_p2p_tcp": "{{ ethereum_node_cl_ports_p2p_tcp }}"
      "{{ ethereum_node_cl }}_ports_p2p_udp": "{{ ethereum_node_cl_ports_p2p_udp }}"
      "{{ ethereum_node_cl }}_ports_http_beacon": "{{ ethereum_node_cl_ports_http_beacon }}"
      "{{ ethereum_node_cl }}_ports_metrics": "{{ ethereum_node_cl_ports_metrics }}"
      "{{ ethereum_node_cl }}_ports_quic": "{{ ethereum_node_cl_ports_quic | default(omit) }}"
      "{{ ethereum_node_cl }}_container_networks": "{{ ethereum_node_docker_networks }}"
      "{{ ethereum_node_cl }}_container_pull": "{{ ethereum_node_images_always_pull }}"
      "{{ ethereum_node_cl }}_execution_engine_endpoint": "{{ ethereum_node_execution_engine_endpoint }}"
      "{{ ethereum_node_cl }}_beacon_endpoint": "{{ ethereum_node_beacon_endpoint | default(ethereum_node_beacon_grpc_endpoint) | default(omit) }}"
      "{{ ethereum_node_cl }}_validator_enabled": "{{ ethereum_node_cl_validator_enabled }}"
      "{{ ethereum_node_cl }}_validator_container_networks": "{{ ethereum_node_docker_networks }}"
      "{{ ethereum_node_cl }}_validator_fee_recipient": "{{ ethereum_node_cl_validator_fee_recipient }}"
      "{{ ethereum_node_cl }}_mev_boost_enabled": "{{ ethereum_node_external_builder_enabled }}"
      "{{ ethereum_node_cl }}_mev_boost_endpoint": "{{ ethereum_node_external_builder_endpoint }}"
      "{{ ethereum_node_cl }}_checkpoint_sync_enabled": "{{ ethereum_node_cl_checkpoint_sync_enabled }}"
      "{{ ethereum_node_cl }}_ipv6_enabled": "{{ ethereum_node_ipv6_enabled }}"
      "{{ ethereum_node_cl }}_supernode_enabled": "{{ ethereum_node_cl_supernode_enabled }}"

- name: "Consensus client: {{ ethereum_node_cl }}"
  ansible.builtin.include_role:
    name: "ethpandaops.general.{{ ethereum_node_cl }}"
  vars: ethereum_node_dynamic_cl_vars
